### PR TITLE
#42: Add `merchantPortalOrderUrl` to Payment model

### LINKED ISSUE #42: Error instantiating Payment object from DeferredPaymentAuth response
Hi,

I'm creating a deferred payment auth request and then trying to instantiate a payment object based on the response's parsed body, ie. basically this
```php
/** @var \Afterpay\SDK\HTTP\Request\DeferredPaymentAuth $request */
$request->send();
$response = $request->getResponse();
$body = $response->getParsedBody();
$payment = new Afterpay\SDK\Model\Payment($body);
```

This was working on 1.1.0 and I think [this change](https://github.com/afterpay/sdk-php/pull/26/files) might have lead it to stop working. The new `merchantPortalOrderUrl` property is causing a call to `setMerchantPortalOrderUrl()` which doesn't exist (see stacktrace below). So I was wondering if the approach above is incorrect in some way, or is the error unexpected? What's the supported way to instantiate an `Afterpay\SDK\Model\Payment` from a deferred payment response?

Thanks in advance!

```
Stacktrace (most recent call first):

  File "/mnt/www/html/myproject/vendor/afterpay-global/afterpay-sdk-php/src/Shared/ModelMethods.php", line 344, in Afterpay\SDK\Model::__call
    throw new \Exception('Call to undefined method ' . get_class($this) . "::{$name}");
  File "/mnt/www/html/myproject/vendor/afterpay-global/afterpay-sdk-php/src/Shared/ModelMethods.php", line 256, in Afterpay\SDK\Model::passConstructArgsToMagicSetters
    $this->{ 'set' . ucfirst($propertyName) }($value);
  File "/mnt/www/html/myproject/vendor/afterpay-global/afterpay-sdk-php/src/Model.php", line 95, in Afterpay\SDK\Model::__construct
    $this->passConstructArgsToMagicSetters(... $args);
  File "/modules/contrib/commerce_afterpay/src/Client/Client.php", line 155, in Drupal\commerce_afterpay\Client\Client::auth
    $payment = new AfterpayPayment($body);
  File "/modules/contrib/commerce_afterpay/src/Plugin/Commerce/PaymentGateway/AfterpayGateway.php", line 136, in Drupal\commerce_afterpay\Plugin\Commerce\PaymentGateway\AfterpayGateway::onReturn
    $payment = $this->getClient()->auth($token);
  File "/modules/contrib/commerce/modules/payment/src/Controller/PaymentCheckoutController.php", line 98, in Drupal\commerce_payment\Controller\PaymentCheckoutController::returnPage
    $payment_gateway_plugin->onReturn($order, $request);
  File "/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php", line 123, in Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber::Drupal\Core\EventSubscriber\{closure}
    return call_user_func_array($controller, $arguments);
  File "/core/lib/Drupal/Core/Render/Renderer.php", line 573, in Drupal\Core\Render\Renderer::executeInRenderContext
    $result = $callable();
  File "/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php", line 124, in Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber::wrapControllerExecutionInRenderContext
    });
  File "/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php", line 97, in Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber::Drupal\Core\EventSubscriber\{closure}
    return $this->wrapControllerExecutionInRenderContext($controller, $arguments);
...
(11 additional frame(s) were not displayed)

Exception: Call to undefined method Afterpay\SDK\Model\Payment::setMerchantPortalOrderUrl in Afterpay\SDK\Model->__call() (line 344 of /mnt/www/html/myproject/vendor/afterpay-global/afterpay-sdk-php/src/Shared/ModelMethods.php).

```

### PR DESCRIPTION
**Pull request by benfterpay**
Closes #42.

### CODE REVIEW

File: test/Integration/DeferredPaymentAuthIntegrationTest.php [hunk 1]
```diff
@@ -76,9 +76,18 @@ public function testApproved201()
...
-        $this->assertEquals('APPROVED', $deferredPaymentAuthResponse->getParsedBody()->status);
+        $this->assertEquals('APPROVED', $deferredPaymentAuthResponseBody->status);
+
+        /**
+         * Also verify that the parsed response can be used to instantiate a Payment object.
+         *
+         * @since 1.3.7
+         */
+
+        $payment = new \Afterpay\SDK\Model\Payment($deferredPaymentAuthResponseBody);
```
Comment (benfterpay) [inline test/Integration/DeferredPaymentAuthIntegrationTest.php:90]: @andriokha adding this line on 1.3.6 caused the test to fail due to:

```
Afterpay\SDK\Test\Integration\DeferredPaymentAuthIntegrationTest::testApproved201
Exception: Call to undefined method Afterpay\SDK\Model\Payment::setMerchantPortalOrderUrl
```

With the change to the Payment model, the test passes.

**Review by chesterz-afterpay — APPROVED** [review]
