### ISSUE TITLE
Error instantiating Payment object from DeferredPaymentAuth response

### ISSUE THREAD

**Issue by andriokha** [afterpay/sdk-php#42]
Hi,

I'm creating a deferred payment auth request and then trying to instantiate a payment object based on the response's parsed body, ie. basically this
```php
/** @var \Afterpay\SDK\HTTP\Request\DeferredPaymentAuth $request */
$request->send();
$response = $request->getResponse();
$body = $response->getParsedBody();
$payment = new Afterpay\SDK\Model\Payment($body);
```

This was working on 1.1.0 and I think [this change](https://github.com/afterpay/sdk-php/pull/26/files) might have lead it to stop working. The new `merchantPortalOrderUrl` property is causing a call to `setMerchantPortalOrderUrl()` which doesn't exist (see stacktrace below). So I was wondering if the approach above is incorrect in some way, or is the error unexpected? What's the supported way to instantiate an `Afterpay\SDK\Model\Payment` from a deferred payment response?

Thanks in advance!

```
Stacktrace (most recent call first):

  File "/mnt/www/html/myproject/vendor/afterpay-global/afterpay-sdk-php/src/Shared/ModelMethods.php", line 344, in Afterpay\SDK\Model::__call
    throw new \Exception('Call to undefined method ' . get_class($this) . "::{$name}");
  File "/mnt/www/html/myproject/vendor/afterpay-global/afterpay-sdk-php/src/Shared/ModelMethods.php", line 256, in Afterpay\SDK\Model::passConstructArgsToMagicSetters
    $this->{ 'set' . ucfirst($propertyName) }($value);
  File "/mnt/www/html/myproject/vendor/afterpay-global/afterpay-sdk-php/src/Model.php", line 95, in Afterpay\SDK\Model::__construct
    $this->passConstructArgsToMagicSetters(... $args);
  File "/modules/contrib/commerce_afterpay/src/Client/Client.php", line 155, in Drupal\commerce_afterpay\Client\Client::auth
    $payment = new AfterpayPayment($body);
  File "/modules/contrib/commerce_afterpay/src/Plugin/Commerce/PaymentGateway/AfterpayGateway.php", line 136, in Drupal\commerce_afterpay\Plugin\Commerce\PaymentGateway\AfterpayGateway::onReturn
    $payment = $this->getClient()->auth($token);
  File "/modules/contrib/commerce/modules/payment/src/Controller/PaymentCheckoutController.php", line 98, in Drupal\commerce_payment\Controller\PaymentCheckoutController::returnPage
    $payment_gateway_plugin->onReturn($order, $request);
  File "/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php", line 123, in Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber::Drupal\Core\EventSubscriber\{closure}
    return call_user_func_array($controller, $arguments);
  File "/core/lib/Drupal/Core/Render/Renderer.php", line 573, in Drupal\Core\Render\Renderer::executeInRenderContext
    $result = $callable();
  File "/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php", line 124, in Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber::wrapControllerExecutionInRenderContext
    });
  File "/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php", line 97, in Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber::Drupal\Core\EventSubscriber\{closure}
    return $this->wrapControllerExecutionInRenderContext($controller, $arguments);
...
(11 additional frame(s) were not displayed)

Exception: Call to undefined method Afterpay\SDK\Model\Payment::setMerchantPortalOrderUrl in Afterpay\SDK\Model->__call() (line 344 of /mnt/www/html/myproject/vendor/afterpay-global/afterpay-sdk-php/src/Shared/ModelMethods.php).

```

**Comment by benfterpay** [comment]
Hi @andriokha,

Thanks for reporting this behaviour, and including these valuable details.

On first inspection this appears to be a valid scenario. Instantiating a Payment object using the parsed response from the API is expected to be supported. Possibly the new `merchantPortalOrderUrl` property just needs to be added to the Payment model. The team will review further.

Thank you.

**Comment by andriokha** [comment]
Thanks @benfterpay for the quick response!

We've worked around it for the time being with a simple `unset($body->merchantPortalOrderUrl)` and I'd be happy to help verify a fix.

Thanks again!
